[package]
name = "app_task_mgmt"
authors = ["Puttipong Dou."]
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "1.4", features = ["sqlite", "r2d2", "chrono"] }
dotenv = "0.15"
actix-rt = "2.0"
uuid = { version = "1.0", features = ["v4"] }
